[package]
name = "browser-engineering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "braus"
path = "src/main.rs"

[dependencies]
clap = "3.2.14"
